// <auto-generated />
using System;
using ControleFinanceiro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleFinanceiro.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.Cartoes.Cartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ContaBancariaPagamentoPadraoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DiaFechamentoFatura")
                        .HasColumnType("integer");

                    b.Property<int>("DiaVencimentoFatura")
                        .HasColumnType("integer");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LimiteCredito")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroFinal")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaPagamentoPadraoId");

                    b.HasIndex("FamiliaId");

                    b.ToTable("cartoes", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.ContasBancarias.ContaBancaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Agencia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataSaldoInicial")
                        .HasColumnType("date");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("LimiteCartoesCompartilhado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroConta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoConta")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("contas_bancarias", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ContaPaiId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EhPadraoRecebimentoFaturaCartao")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsavelPadraoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasFilter("\"Codigo\" IS NOT NULL");

                    b.HasIndex("ContaPaiId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("ResponsavelPadraoId");

                    b.HasIndex("Tipo", "Ativo");

                    b.ToTable("contas_gerenciais", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.FormasPagamento.FormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<bool>("BaixarAutomaticamente")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("EhCartao")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("formas_pagamento", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CpfCnpj")
                        .IsUnique()
                        .HasFilter("\"CpfCnpj\" IS NOT NULL");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("Nome");

                    b.HasIndex("Ativo", "Nome");

                    b.ToTable("pessoas", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.Pessoas.PessoaChavePix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId", "Tipo", "Chave")
                        .IsUnique();

                    b.ToTable("pessoas_chaves_pix", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AiConversa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<string>("ContatoExterno")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ai_conversas", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AiMensagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.HasIndex("ExternalMessageId");

                    b.ToTable("ai_mensagens", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AiToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeFerramenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TokensEntrada")
                        .HasColumnType("integer");

                    b.Property<int>("TokensSaida")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConversaId");

                    b.ToTable("ai_tool_calls", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AlertaWhatsappEnviado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveReferencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataEnvio")
                        .HasColumnType("date");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlertasWhatsappEnviados");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.WhatsappConfigAlerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DiasAntecedenciaVencimento")
                        .HasColumnType("integer");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ReceberLimiteCategoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceberLimiteResponsavel")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReceberVencimento")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("whatsapp_config_alertas", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.WhatsappUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("VerificadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("Telefone");

                    b.HasIndex("UsuarioId");

                    b.ToTable("whatsapp_usuarios", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.ContaPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveSerieImportacaoCartao")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("ContaBancariaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataLiquidacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FaturaCartaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormaPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrupoParcelamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("OrigemCompraPlanejadaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrigemImportacaoWhatsappId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecebedorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RegraRecorrenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsavelCompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusContaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorJuros")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMulta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("DataEmissao");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("Descricao");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("FaturaCartaoId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("GrupoParcelamentoId");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("OrigemCompraPlanejadaId");

                    b.HasIndex("OrigemImportacaoWhatsappId");

                    b.HasIndex("RegraRecorrenciaId");

                    b.HasIndex("ResponsavelCompraId");

                    b.HasIndex("RecebedorId", "StatusContaId");

                    b.HasIndex("StatusContaId", "DataVencimento");

                    b.HasIndex("CartaoId", "ChaveSerieImportacaoCartao", "NumeroParcela", "QuantidadeParcelas")
                        .HasFilter("\"CartaoId\" IS NOT NULL AND \"ChaveSerieImportacaoCartao\" IS NOT NULL");

                    b.ToTable("contas_pagar", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.ContaReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaBancariaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataLiquidacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EhRecorrente")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormaPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GrupoParcelamentoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("PagadorId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantidadeParcelas")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RegraRecorrenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusContaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorJuros")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMulta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("DataEmissao");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("RegraRecorrenciaId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("PagadorId", "StatusContaId");

                    b.HasIndex("StatusContaId", "DataVencimento");

                    b.ToTable("contas_receber", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.FaturaCartao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid?>("ContaBancariaPagamentoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaPagamentoId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("CartaoId", "Competencia")
                        .IsUnique();

                    b.ToTable("faturas_cartao", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.MetaOrcamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid>("ContaGerencialId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorMeta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGerencialId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("FamiliaId", "ContaGerencialId", "Competencia")
                        .IsUnique();

                    b.ToTable("metas_orcamento", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.MovimentacaoFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaBancariaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaPagarId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaReceberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataMovimentacao")
                        .HasColumnType("date");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FaturaCartaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("StatusMovimentacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaPagarId");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("DataMovimentacao");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("FaturaCartaoId");

                    b.HasIndex("ContaBancariaId", "DataMovimentacao");

                    b.HasIndex("StatusMovimentacaoId", "DataMovimentacao");

                    b.HasIndex("Natureza", "StatusMovimentacaoId", "DataMovimentacao");

                    b.ToTable("movimentacoes_financeiras", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.RateioContaGerencial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaGerencialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaPagarId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaReceberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Percentual")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGerencialId");

                    b.HasIndex("ContaPagarId");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("FamiliaId");

                    b.ToTable("rateios_conta_gerencial", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.RegraRecorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<int>("DiaOrdemMensal")
                        .HasColumnType("integer");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("PermiteEdicaoOcorrenciaIndividual")
                        .HasColumnType("boolean");

                    b.Property<string>("TemplateJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoPeriodicidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("TipoLancamento", "Ativa");

                    b.ToTable("regras_recorrencia", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.StatusConta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("status_conta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Codigo = "PENDENTE",
                            Nome = "Pendente"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Codigo = "LIQUIDADA",
                            Nome = "Liquidada"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Codigo = "VENCIDA",
                            Nome = "Vencida"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Codigo = "CANCELADA",
                            Nome = "Cancelada"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Codigo = "PARCIAL",
                            Nome = "Parcial"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Codigo = "EM_FATURA",
                            Nome = "Em fatura"
                        });
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.StatusMovimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("status_movimentacao", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Codigo = "PREVISTA",
                            Nome = "Prevista"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Codigo = "EFETIVADA",
                            Nome = "Efetivada"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Codigo = "CANCELADA",
                            Nome = "Cancelada"
                        });
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.ConviteFamilia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AceitoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("EmailConvidado")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime>("ExpiraEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("UsuarioAceiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("convites_familia", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("familias", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.MembroFamilia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("FamiliaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("membros_familia", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiraEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevogadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubstituidoPorTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("FamiliaAtivaId")
                        .HasColumnType("uuid");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.ImportacoesWhatsapp.ImportacaoWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("ConfiancaExtracao")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("ConfirmadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomeArquivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecebidoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RejeitadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remetente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TextoBruto")
                        .HasColumnType("text");

                    b.Property<string>("TipoOrigem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("Status");

                    b.ToTable("importacoes_whatsapp", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.ImportacoesWhatsapp.ItemImportadoWhatsapp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveAprendizado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ConfirmadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContaGerencialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaReceberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DescricaoAjustada")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ImportacaoWhatsappId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MarcarComoRecorrente")
                        .HasColumnType("boolean");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PayloadSugeridoJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejeitadoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoSugestao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAprendizado");

                    b.HasIndex("ContaGerencialId");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("ImportacaoWhatsappId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("itens_importados_whatsapp", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.PlanejamentoCompras.PlanejamentoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaGerencialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContaPagarGeradaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConvertidaEmContaPagarEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DataDesejada")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Parcelavel")
                        .HasColumnType("boolean");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("QuantidadeParcelasDesejada")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResponsavelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("ValorEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGerencialId");

                    b.HasIndex("ContaPagarGeradaId");

                    b.HasIndex("FamiliaId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("compras_planejadas", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Infrastructure.Persistence.AuditTrailEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("audit_trail_entries", (string)null);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.Cartoes.Cartao", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasBancarias.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaPagamentoPadraoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", null)
                        .WithMany()
                        .HasForeignKey("ContaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelPadraoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.Pessoas.PessoaChavePix", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany("ChavesPix")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AiMensagem", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.FinanceAI.AiConversa", null)
                        .WithMany("Mensagens")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AiToolCall", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.FinanceAI.AiConversa", null)
                        .WithMany("ToolCalls")
                        .HasForeignKey("ConversaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.WhatsappConfigAlerta", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.WhatsappUsuario", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.ContaPagar", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Cartoes.Cartao", null)
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasBancarias.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.FaturaCartao", null)
                        .WithMany()
                        .HasForeignKey("FaturaCartaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.FormasPagamento.FormaPagamento", null)
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.PlanejamentoCompras.PlanejamentoCompra", null)
                        .WithMany()
                        .HasForeignKey("OrigemCompraPlanejadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.ImportacoesWhatsapp.ImportacaoWhatsapp", null)
                        .WithMany()
                        .HasForeignKey("OrigemImportacaoWhatsappId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("RecebedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.RegraRecorrencia", null)
                        .WithMany()
                        .HasForeignKey("RegraRecorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelCompraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.StatusConta", null)
                        .WithMany()
                        .HasForeignKey("StatusContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.ContaReceber", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Cartoes.Cartao", null)
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasBancarias.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.FormasPagamento.FormaPagamento", null)
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PagadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.RegraRecorrencia", null)
                        .WithMany()
                        .HasForeignKey("RegraRecorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.StatusConta", null)
                        .WithMany()
                        .HasForeignKey("StatusContaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.FaturaCartao", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Cartoes.Cartao", null)
                        .WithMany()
                        .HasForeignKey("CartaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasBancarias.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.MetaOrcamento", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", null)
                        .WithMany()
                        .HasForeignKey("ContaGerencialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.MovimentacaoFinanceira", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasBancarias.ContaBancaria", null)
                        .WithMany()
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.ContaPagar", null)
                        .WithMany()
                        .HasForeignKey("ContaPagarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.ContaReceber", null)
                        .WithMany()
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.FaturaCartao", null)
                        .WithMany()
                        .HasForeignKey("FaturaCartaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.StatusMovimentacao", null)
                        .WithMany()
                        .HasForeignKey("StatusMovimentacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Financeiro.RateioContaGerencial", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", null)
                        .WithMany()
                        .HasForeignKey("ContaGerencialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.ContaPagar", null)
                        .WithMany()
                        .HasForeignKey("ContaPagarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.ContaReceber", null)
                        .WithMany()
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.ConviteFamilia", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Identidade.Familia", null)
                        .WithMany()
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.MembroFamilia", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Identidade.Familia", null)
                        .WithMany("Membros")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Identidade.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.RefreshToken", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.ImportacoesWhatsapp.ItemImportadoWhatsapp", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", null)
                        .WithMany()
                        .HasForeignKey("ContaGerencialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.ContaReceber", null)
                        .WithMany()
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.ImportacoesWhatsapp.ImportacaoWhatsapp", null)
                        .WithMany("Itens")
                        .HasForeignKey("ImportacaoWhatsappId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.PlanejamentoCompras.PlanejamentoCompra", b =>
                {
                    b.HasOne("ControleFinanceiro.Domain.Cadastros.ContasGerenciais.ContaGerencial", null)
                        .WithMany()
                        .HasForeignKey("ContaGerencialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleFinanceiro.Domain.Financeiro.ContaPagar", null)
                        .WithMany()
                        .HasForeignKey("ContaPagarGeradaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Cadastros.Pessoas.Pessoa", b =>
                {
                    b.Navigation("ChavesPix");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.FinanceAI.AiConversa", b =>
                {
                    b.Navigation("Mensagens");

                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.Identidade.Familia", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("ControleFinanceiro.Domain.ImportacoesWhatsapp.ImportacaoWhatsapp", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
