sonar.projectKey=controle-financeiro-backend
sonar.projectName=controle-financeiro-backend
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=**/TestResults/coverage/coverage.opencover.xml,**/coverage.opencover.xml
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**
